---
# model: gemini-2.0-flash-exp
# model: google/gemini-2.0-flash-exp:free
# model: microsoft/phi-3-medium-128k-instruct:free
model: hermes3:8b-llama3.1-q6_K
useTools: true
# systemPrompt: >
#   You are a helpful assistant with the ability to reason. Please think deeply before responding.
systemPrompt: >
  You are a helpful assistant with have access to an advanced search engine. Please provide the
  user with the information they are looking for by using the search tool provided.
