---
model: hermes3:8b-llama3.1-q6_K
useTools: true
systemPrompt: >
  You are a helpful assistant with have access to an advanced search engine. Please provide the
  user with the information they are looking for by using the search tool provided.