name: "Pull Request"
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@master
      - name: Enter nix shell and run bun tests
        env:
          ACTIONS_STEP_DEBUG: 'true'
        run: |
          nix develop
          echo $PATH
          ls -a
          /nix/store/738z8xcfqmxd60dc74n02bmc8awa0mrg-bun-1.2.0/bin/bun --env-file=.env.test test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@master
      - name: Run `nix build`
        run: |
          nix build
          result/bin/app --help
