name: "Pull Request"
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@master
      - name: Enter nix shell and run bun tests
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        env:
          ACTIONS_STEP_DEBUG: 'true'
        run: |
          nix develop
          echo $PATH
          type bun
          bun install --no-progress --frozen-lockfile
          bun --env-file=.env.test test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@master
      - name: Run `nix build`
        run: |
          nix build
          result/bin/app --help
