name: "Pull request"
on:
  pull_request:

jobs:
  test-and-build:
    name: Test/build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Check Nix flake
        run: nix flake check --all-systems
      - name: Bun tests
        run: |
          nix develop --command bash -c '
            bun install --no-progress --frozen-lockfile
            bun --env-file=.env.test test
          '
      - run: Nix build
      - name: Check built chat-thyme app help menu
        run: result/bin/app --help

  lint-and-format:
    name: Lint/format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci --changed --no-errors-on-unmatched

  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build Check Docker build entrypoint help menu
        run: docker build . -t ghcr.io/chilir/chat-thyme:${{ github.event.pull_request.head.sha }}
      - name: Check containerized chat-thyme app help menu
          docker run \
            --rm \
            --entrypoint /app/bin/app \
            ghcr.io/chilir/chat-thyme:${{ github.event.pull_request.head.sha }} \
            --help